### ISSUE TITLE
Create detailed analysis of data flow through mod-data-export-spring

### ISSUE THREAD

**Issue by ncovercash** [ualibweb/mod-data-export-spring#4]

**Comment by sjturner-ua** [comment]
Hey, when you do this, can you include a flow chart? (whoever does this)

**Comment by ncovercash** [comment]
@sjturner-ua what are you looking for, particularly?

**Comment by nhanaa** [comment]
Not exactly flowcharts but here are some sequence diagrams I made while investigating how the process works in MDES when making some specific requests to the API:

- POST request to upsert a job into MDES: [Imgur](https://i.imgur.com/nUUZK5M.png)
- GET request to download a job from MDES: [Imgur](https://i.imgur.com/V8N97sQ.png)
- Receive updated job through kafka from Worker: [Imgur](https://i.imgur.com/krqVrRT.png)

**Comment by sjturner-ua** [comment]
Awesome!

**Comment by nhanaa** [comment]
The MDES is a REST API that let us create, update, and delete export jobs. The jobs created by MDES are stored in a PostgreSQL database. MDES communicates with MDEW through Kafka. 

To create/update a job, we make a POST request to the /jobs endpoint. Everything after that happens afterward mainly in `org.folio.des.service.impl.JobServiceImpl` and can be observed from the first diagram above.

**Comment by nhanaa** [comment]
To download an exported file, we can make a GET request to the MDES Spring API. From then, the process follows the diagram above. Note that the file will be downloaded using a URL generated from the filename. The URL is retrieved using the API to `/refresh-presigned-url` endpoint in the MDEW API.

**Comment by nhanaa** [comment]
MDES receives job updates through Kafka which are sent by MDEW. Kafka uses a listener which is defined in `org.folio.des.service.JobUpdatesService` to listen to updates from MDEW and retrieve them. The job updates are then also updated in the database, which includes available link to download the exported file which can be retrieved as mentioned above.

**Comment by nhanaa** [comment]
@sjturner-ua @ncovercash @GoZaddy
